### ISSUE TITLE
AC Meter AT3010

### ISSUE THREAD

**Issue by Nuqvxz** [NiceLabs/atorch-console#8]
Setting the backlight time
--------------------------------------
```
FF 55 11 01 21 00 00 00 00 77   =  0 OFF
FF 55 11 01 21 00 00 00 01 70   =  1
FF 55 11 01 21 00 00 00 02 71   =  2
FF 55 11 01 21 00 00 00 09 78   =  9
FF 55 11 01 21 00 00 00 0A 79   = 10
FF 55 11 01 21 00 00 00 2F 26   = 47
FF 55 11 01 21 00 00 00 3B 2A   = 59
FF 55 11 01 21 00 00 00 3C 2B   = 60 ON
```

"End byte" `3C` - backlight time

Tariff setting
--------------------------------------
```
FF 55 11 01 22 00 0F 42 3F 80   = 9999.99 [0F423F = 999999]
FF 55 11 01 22 00 00 00 01 71   =    0.01 [000001 = 000001]
```

Reset
--------------------------------------
```
FF 55 11 01 01 00 00 00 00 57
```

**Comment by septs** [comment]
"Tariff setting" the settings Chinese name is "电价设置范围"?
![image](https://user-images.githubusercontent.com/3842474/90717403-16ba0f00-e2e2-11ea-951e-d136e5a435c4.png)

**Comment by Nuqvxz** [comment]
In the English language manual, this is called:

> "Electricity price setting range: 0000.00~9999.99 $ Resolution accuracy: 0.0.1 yuan or other country"

**Comment by septs** [comment]
https://github.com/NiceLabs/atorch-console/runs/1006162039?check_suite_focus=true#step:6:33

![image](https://user-images.githubusercontent.com/3842474/90718790-68b06400-e2e5-11ea-87ed-5328129e9013.png)

unit test coverage the feature.

thank you for the use case

**Comment by septs** [comment]
> `FF 55 11 01 01 00 00 00 00 57`

the reset command, reset all fields?
there are other **reset commands**?

**Comment by septs** [comment]
new release, deployed to gh-pages
plz try use it.

**Comment by Nuqvxz** [comment]
`FF 55 11 01 01 00 00 00 00 57`
Reset: Electricity (kWh), Carbon dioxide (kg), Electricity charges ($)

**Comment by septs** [comment]
@Nuqvxz How do you think this feature should be named?

Reset without Duration?
Other idea?
