### ISSUE TITLE
Unable to connect to DT3010

### ISSUE THREAD

**Issue by mjrsnyder** [NiceLabs/atorch-console#9]
After downloading this project and running `npm run start` and going to the url provided in the terminal I clicked `Connect` and nothing happens.  I get the error in the console screenshot below.

![Screenshot from 2020-11-17 21-40-26](https://user-images.githubusercontent.com/2317378/99476045-d2a8cb80-291d-11eb-8482-9bfe96b2c64f.png)

Am I running this application correctly?

I'm on Ubuntu 20.04 with the distro versions of node and npm installed.  I can see the DT3010 in the list of bluetooth devices and can connect from the OS.  I tested atorch-console both connected from the OS and not.

Thanks for your help!

**Comment by septs** [comment]
Enable `chrome://flags/#enable-experimental-web-platform-features` and restart Chrome.

Web Bluetooth is Chrome only (see https://caniuse.com/web-bluetooth)
